CREATE DATABASE jobportal;
use jobportal;
CREATE TABLE `jobportal`.`users` (`id` INT NOT NULL AUTO_INCREMENT , `username` VARCHAR(200) NOT NULL , `email` VARCHAR(200) NOT NULL , `password` VARCHAR(200) NOT NULL , `img` VARCHAR(200) NOT NULL , `cv` VARCHAR(200) NULL DEFAULT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
select * from users;
ALTER TABLE `users` CHANGE `password` `mypassword` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL;
ALTER TABLE `users` ADD `type` VARCHAR(200) NOT NULL AFTER `img`;
ALTER TABLE `users` ADD `title` VARCHAR(200) NULL DEFAULT NULL AFTER `cv`, ADD `bio` VARCHAR(500) NULL DEFAULT NULL AFTER `title`, ADD `facebook` VARCHAR(200) NULL DEFAULT NULL AFTER `bio`, ADD `twitter` VARCHAR(200) NULL DEFAULT NULL AFTER `facebook`, ADD `LinkedIn` VARCHAR(200) NULL DEFAULT NULL AFTER `twitter`;
DELETE FROM users WHERE img='jobportal.jpg';
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE users RENAME Column LinkedIn TO linkedin;
CREATE TABLE `jobportal`.`jobs` (`id` INT NOT NULL AUTO_INCREMENT , `job_title` VARCHAR(200) NOT NULL , `job_region` VARCHAR(200) NOT NULL , `job_type` VARCHAR(200) NOT NULL , `vacancy` INT NOT NULL , `experience` VARCHAR(200) NOT NULL , `salary` VARCHAR(200) NOT NULL , `gender` VARCHAR(200) NOT NULL , `application_deadline` TEXT NOT NULL , `job_description` TEXT NOT NULL , `responsibilities` TEXT NOT NULL , `education_experience` TEXT NOT NULL , `other_benifits` TEXT NOT NULL , `company_email` VARCHAR(200) NOT NULL , `company_name` VARCHAR(200) NOT NULL , `company_id` INT NOT NULL , `company_image` VARCHAR(200) NOT NULL , `status` INT NOT NULL DEFAULT '0' , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
select * from jobs;
DROP TABLE jobs;
UPDATE jobs SET status = 1 WHERE id = 26;
CREATE TABLE `jobportal`.`categories` (`id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(200) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `categories` (`id`, `name`, `created_at`) VALUES (NULL, 'design', CURRENT_TIMESTAMP), (NULL, 'development', CURRENT_TIMESTAMP);
SELECT * FROM `categories`;
SELECT * FROM `job_applications`;
ALTER TABLE `jobs` ADD `job_category` VARCHAR(200) NOT NULL AFTER `vacancy`;
CREATE TABLE `jobportal`.`job_applications` (`id` INT NOT NULL AUTO_INCREMENT , `username` VARCHAR(200) NOT NULL , `email` VARCHAR(200) NOT NULL , `cv` VARCHAR(200) NOT NULL , `worker_id` INT NOT NULL , `job_id` INT NOT NULL , `job_title` VARCHAR(200) NOT NULL , `company_id` INT NOT NULL , `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `jobportal`.`saved_jobs` (`id` INT NOT NULL AUTO_INCREMENT , `job_id` INT NOT NULL , `worker_id` INT NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
SELECT * FROM `saved_jobs`;
SELECT * FROM jobs JOIN saved_jobs ON jobs.id = saved_jobs.job_id;
CREATE TABLE `jobportal`.`searches` (`id` INT NOT NULL AUTO_INCREMENT , `keyword` VARCHAR(200) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `jobportal`.`admins` (`id` INT NOT NULL AUTO_INCREMENT , `adminname` VARCHAR(200) NOT NULL , `email` VARCHAR(200) NOT NULL , `mypassword` VARCHAR(200) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `admins` (`id`, `adminname`, `email`, `mypassword`, `created_at`) VALUES (NULL, 'admin@gamil.com', 'admin@gamil.com', '$2y$10$.KderwNHnmiMEIaEzGw3IOKC/0r8pRZKiOWzG0tF1gvZr2EfB6wTK', CURRENT_TIMESTAMP);
select * from admins;